name: Pipeline Integrado

on:
  push:
    branches: [ "main" ]

jobs:
  # 1ª ETAPA: TESTE
  teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Instalar dependências e rodar testes
        run: |
          pip install fastapi uvicorn pydantic pytest pytest-asyncio httpx
          pytest test_main.py

  # 2ª ETAPA: ENTREGA (Depende do teste)
  entrega:
    needs: teste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gerar artefato
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: main.py

  # 3ª ETAPA: DOCKER (Depende da entrega)
  docker:
    needs: entrega
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build e Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest

  # 4ª ETAPA: IMPLANTAR (Depende do docker)
  implantar:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Simular Deploy
        run: echo "Executando deploy final..."

  # 5ª ETAPA: DISCÓRDIA (Depende do implantar)
  discórdia:
    needs: implantar
    if: always() # Para avisar você mesmo se algo falhar no caminho
    runs-on: ubuntu-latest
    steps:
      - name: Notificar no Discord
        uses: sniddl/discord-commits@v1.6
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          template: "Pipeline de 5 etapas concluído! Status: ${{ job.status }}"
