name: Continuous Delivery

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar artefato
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            main.py
            README.md

  deploy:
    needs: delivery
    runs-on: ubuntu-latest

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: projetozipado

      - name: Simular deploy

        run: ls -R

        name: ci

  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v4
        
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v47
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: user/app:latest
        run: ls -R
