name: Continuous Delivery

on:
  pull_request:

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo "Build ok"

  docker:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t minha-api .

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy
        run: echo "Deploy ok"