Nome : Entrega Contínua

sobre :
  empurrar :
    galhos :
      - principal

empregos :
  entrega :
    runs-on : ubuntu-latest

    passos :
      - nome : Finalizar compra do código
        utiliza : actions/checkout@v4

      - nome : Gerar artefato
        utiliza : actions/upload-artifact@v4
        com :
          nome : projetozipado
          caminho : |
            main.py
            README.md
  docker :
    runs-on : ubuntu-latest
    necessidades : entrega

    passos :
      - nome : Finalizar compra
        utiliza : actions/checkout@v4

      - nome : Configurar QEMU
        usa : docker/setup-qemu-action@v3

      - nome : Configurar Docker Buildx
        usa : docker/setup-buildx-action@v3

      - nome : Criar imagem Docker
        usa : docker/build-push-action@v6
        com :
          contexto : .
          empurrar : falso
          tags : minha-api:latest

  implantar :
    runs-on : ubuntu-latest
    Requisitos : Docker

    passos :
      - nome : Baixar artefato
        utiliza : actions/download-artifact@v4
        com :
          nome : projetozipado

      - nome : Implantação simulada
        executar : ls -R

      - nome : Implantação simulada
        run : echo "deploy realizado com sucesso"
        
  discord :
    runs-on : ubuntu-latest
    necessidades : implantar

    passos :
      - nome : Notificar no Discord
        usa : sniddl/discord-commits@v1.6
        com :
          webhook : ${{ secrets.DISCORD_WEBHOOK }}
